import {
  Cliente,
  Veiculo,
  Servico,
  Agendamento,
  Payment,
  CashRegister,
  CashMovement,
  CommunicationLog,
  Profile,
  AuditLog,
  BusinessSettings,
  BusinessHour,
  ScheduleBlock,
  VehicleCheckin,
  ServiceReview,
  CustomerTag,
  CustomerTagAssignment,
} from "@/types";

export const INITIAL_SERVICOS: Servico[] = [
  {
    id: "srv-1",
    numero: 1,
    nome: "Lavagem simples de moto",
    descricao: "Limpeza completa da lataria, rodas, motor e secagem especializada.",
    preco: 30.0,
    duracao_minutos: 35,
    tipo_veiculo: "Moto",
    ativo: true,
  },
  {
    id: "srv-2",
    numero: 2,
    nome: "Lavagem + aspiração de carro pequeno simples",
    descricao: "Lavagem técnica da lataria, secagem, limpeza de vidros e aspiração interna.",
    preco: 40.0,
    duracao_minutos: 45,
    tipo_veiculo: "Carro pequeno",
    ativo: true,
  },
  {
    id: "srv-3",
    numero: 3,
    nome: "Lavagem + aspiração + cera líquida + hidratação de carro pequeno",
    descricao: "Tratamento completo com cera líquida de alto brilho e hidratação de plásticos/painel.",
    preco: 60.0,
    duracao_minutos: 60,
    tipo_veiculo: "Carro pequeno",
    ativo: true,
  },
  {
    id: "srv-4",
    numero: 4,
    nome: "Lavagem + aspiração de carro SUV simples",
    descricao: "Lavagem da carroceria, rodas, caixas de roda e aspiração interna detalhada.",
    preco: 60.0,
    duracao_minutos: 50,
    tipo_veiculo: "SUV",
    ativo: true,
  },
  {
    id: "srv-5",
    numero: 5,
    nome: "Lavagem + aspiração + cera líquida + hidratação de carro SUV",
    descricao: "Lavagem premium, cera líquida protetora, hidratação de plásticos e acabamentos.",
    preco: 80.0,
    duracao_minutos: 75,
    tipo_veiculo: "SUV",
    ativo: true,
  },
  {
    id: "srv-6",
    numero: 6,
    nome: "Lavagem + aspiração de caminhonete simples",
    descricao: "Limpeza pesada externa, caçamba, rodas e aspiração interna completa.",
    preco: 80.0,
    duracao_minutos: 60,
    tipo_veiculo: "Caminhonete",
    ativo: true,
  },
  {
    id: "srv-7",
    numero: 7,
    nome: "Lavagem + aspiração + cera líquida + hidratação de caminhonete",
    descricao: "Serviço master com proteção de pintura em cera líquida e hidratação de plásticos/borrachas.",
    preco: 100.0,
    duracao_minutos: 90,
    tipo_veiculo: "Caminhonete",
    ativo: true,
  },
];

export const INITIAL_CLIENTES: Cliente[] = [
  {
    id: "cli-1",
    nome: "João Silva",
    whatsapp: "71991234567",
    observacoes: "Cliente regular dos finais de semana. Prefere perfume suave.",
    created_at: "2026-09-10",
    ultimo_atendimento: "Hoje, 08:00",
  },
  {
    id: "cli-2",
    nome: "Carlos Santos",
    whatsapp: "71988776655",
    observacoes: "Atenção especial às rodas e caixas de roda.",
    created_at: "2026-09-15",
    ultimo_atendimento: "Hoje, 09:00",
  },
  {
    id: "cli-3",
    nome: "Mariana Lima",
    whatsapp: "71999881122",
    observacoes: "Mora em condomínio no litoral de Guaraípe.",
    created_at: "2026-09-20",
    ultimo_atendimento: "Hoje, 10:30",
  },
  {
    id: "cli-4",
    nome: "Roberto Alves",
    whatsapp: "71981112233",
    observacoes: "Veículo de praia, costuma vir com areia na caçamba.",
    created_at: "2026-09-25",
    ultimo_atendimento: "Hoje, 11:30",
  },
  {
    id: "cli-5",
    nome: "Lucas Ferreira",
    whatsapp: "71987654321",
    observacoes: "Moto para deslocamento de trabalho.",
    created_at: "2026-09-28",
    ultimo_atendimento: "Ontem, 16:00",
  },
];

export const INITIAL_VEICULOS: Veiculo[] = [
  {
    id: "veic-1",
    cliente_id: "cli-1",
    marca: "Honda",
    modelo: "Civic G10",
    placa: "BRA2E19",
    cor: "Prata",
    tipo: "Carro pequeno",
    observacoes: "Cuidado ao aspirar perto do console central.",
    created_at: "2026-09-10",
  },
  {
    id: "veic-2",
    cliente_id: "cli-2",
    marca: "Toyota",
    modelo: "Corolla XEi",
    placa: "PKT4A90",
    cor: "Preto",
    tipo: "Carro pequeno",
    observacoes: "Pintura escura sensível a microrriscos.",
    created_at: "2026-09-15",
  },
  {
    id: "veic-3",
    cliente_id: "cli-3",
    marca: "Jeep",
    modelo: "Compass Longitude",
    placa: "RDM8F22",
    cor: "Branco Perolizado",
    tipo: "SUV",
    observacoes: "Protetor de carpete no porta-malas.",
    created_at: "2026-09-20",
  },
  {
    id: "veic-4",
    cliente_id: "cli-4",
    marca: "Toyota",
    modelo: "Hilux SRV",
    placa: "OZT9B77",
    cor: "Cinza Granito",
    tipo: "Caminhonete",
    observacoes: "Lavar bem a caçamba e parte inferior.",
    created_at: "2026-09-25",
  },
  {
    id: "veic-5",
    cliente_id: "cli-5",
    marca: "Honda",
    modelo: "CG 160 Titan",
    placa: "RKY3C44",
    cor: "Azul Metálico",
    tipo: "Moto",
    observacoes: "Cuidado com o escapamento quente.",
    created_at: "2026-09-28",
  },
];

export const getTodayDateString = (): string => {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

export const INITIAL_BUSINESS_SETTINGS: BusinessSettings = {
  id: "00000000-0000-0000-0000-000000000010",
  business_name: "Point do Coco Lava Jato",
  commercial_name: "Point do Coco",
  phone: "(71) 9 9288-7645",
  whatsapp: "(71) 9 9288-7645",
  email: "contato@pointdococo.com.br",
  address: "Entrada do bosque Guaraípe, Litoral Norte - BA",
  address_number: "S/N",
  address_complement: "Entrada do bosque",
  neighborhood: "Guaraípe",
  city: "Litoral Norte",
  state: "BA",
  postal_code: "42840-000",
  logo_url: "/images/logo.png",
  description: "Lava Jato especializado em cuidados automotivos de alto padrão no Litoral Norte da Bahia.",
  timezone: "America/Bahia",
  currency: "BRL",
  appointment_interval: 30,
  minimum_advance_minutes: 30,
  maximum_advance_days: 30,
  cancellation_deadline_minutes: 120,
  allow_rescheduling: true,
  reschedule_deadline_minutes: 120,
  buffer_between_services_minutes: 0,
  allow_overbooking: false,
  allow_same_day_booking: true,
  allow_booking_without_plate: false,
  require_phone: true,
  require_name: true,
  whatsapp_enabled: true,
  automatic_confirmation: false,
  automatic_reminder: false,
  automatic_completion_message: false,
  automatic_payment_reminder: false,
  instagram_url: "https://instagram.com/pointdococolavajato",
  require_checkin_to_start: true,
  created_at: "2026-09-01T08:00:00Z",
  updated_at: "2026-09-01T08:00:00Z",
};

export const INITIAL_BUSINESS_HOURS: BusinessHour[] = [
  { id: "bh-0", day_of_week: 0, is_open: false, opening_time: "08:00", closing_time: "12:00", break_start: null, break_end: null }, // Domingo Fechado
  { id: "bh-1", day_of_week: 1, is_open: true,  opening_time: "08:00", closing_time: "18:00", break_start: "12:00", break_end: "13:00" },
  { id: "bh-2", day_of_week: 2, is_open: true,  opening_time: "08:00", closing_time: "18:00", break_start: "12:00", break_end: "13:00" },
  { id: "bh-3", day_of_week: 3, is_open: true,  opening_time: "08:00", closing_time: "18:00", break_start: "12:00", break_end: "13:00" },
  { id: "bh-4", day_of_week: 4, is_open: true,  opening_time: "08:00", closing_time: "18:00", break_start: "12:00", break_end: "13:00" },
  { id: "bh-5", day_of_week: 5, is_open: true,  opening_time: "08:00", closing_time: "18:00", break_start: "12:00", break_end: "13:00" },
  { id: "bh-6", day_of_week: 6, is_open: true,  opening_time: "08:00", closing_time: "18:00", break_start: "12:00", break_end: "13:00" },
];

export const INITIAL_SCHEDULE_BLOCKS: ScheduleBlock[] = [
  {
    id: "blk-1",
    start_datetime: "2026-10-12T00:00:00-03:00",
    end_datetime: "2026-10-12T23:59:59-03:00",
    reason: "Feriado Nacional - N. Sra. Aparecida",
    created_by: "usr-admin-1",
    created_at: "2026-09-20T10:00:00Z",
  },
];

export const INITIAL_PROFILES: Profile[] = [
  {
    id: "usr-admin-1",
    full_name: "Administrador Point do Coco",
    email: "admin@pointdococo.com.br",
    phone: "71992887645",
    role: "admin",
    avatar_url: null,
    active: true,
    created_at: "2026-09-01T08:00:00Z",
    updated_at: "2026-09-01T08:00:00Z",
  },
  {
    id: "usr-manager-1",
    full_name: "Marcos Gerente",
    email: "marcos.gerente@pointdococo.com.br",
    phone: "71988887777",
    role: "manager",
    avatar_url: null,
    active: true,
    created_at: "2026-09-10T09:00:00Z",
    updated_at: "2026-09-10T09:00:00Z",
  },
  {
    id: "usr-employee-1",
    full_name: "Rafael Operador",
    email: "rafael.operador@pointdococo.com.br",
    phone: "71977776666",
    role: "employee",
    avatar_url: null,
    active: true,
    created_at: "2026-09-15T10:00:00Z",
    updated_at: "2026-09-15T10:00:00Z",
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "aud-1",
    user_id: "usr-admin-1",
    user_name: "Administrador Point do Coco",
    action: "settings.updated",
    entity: "settings",
    entity_id: "00000000-0000-0000-0000-000000000010",
    metadata: { section: "empresa", alterado_por: "Administrador" },
    created_at: `${getTodayDateString()}T08:00:00Z`,
  },
  {
    id: "aud-2",
    user_id: "usr-admin-1",
    user_name: "Administrador Point do Coco",
    action: "business_hours.updated",
    entity: "business_hours",
    entity_id: "bh-1",
    metadata: { motivo: "Definição de intervalo de almoço das 12h às 13h" },
    created_at: `${getTodayDateString()}T08:15:00Z`,
  },
];

export const INITIAL_AGENDAMENTOS: Agendamento[] = [
  {
    id: "agd-1",
    code: "PC-100001",
    cancel_token: "tok-sec-agd-1",
    cliente_id: "cli-1",
    cliente_nome: "João Silva",
    cliente_whatsapp: "71991234567",
    veiculo_id: "veic-1",
    veiculo_tipo: "Carro pequeno",
    veiculo_modelo: "Honda Civic",
    veiculo_placa: "BRA2E19",
    servico_id: "srv-2",
    servico_nome: "Lavagem + aspiração de carro pequeno simples",
    valor: 40.0,
    data: getTodayDateString(),
    horario: "08:00",
    status: "Confirmado",
    observacoes: "Chegou no horário",
    created_at: "2026-09-30T10:00:00Z",
  },
  {
    id: "agd-2",
    code: "PC-100002",
    cancel_token: "tok-sec-agd-2",
    cliente_id: "cli-2",
    cliente_nome: "Carlos Santos",
    cliente_whatsapp: "71988776655",
    veiculo_id: "veic-2",
    veiculo_tipo: "Carro pequeno",
    veiculo_modelo: "Toyota Corolla",
    veiculo_placa: "PKT4A90",
    servico_id: "srv-3",
    servico_nome: "Lavagem + aspiração + cera líquida + hidratação de carro pequeno",
    valor: 60.0,
    data: getTodayDateString(),
    horario: "09:00",
    status: "Em atendimento",
    observacoes: "Carro no box 1",
    created_at: "2026-09-30T14:30:00Z",
  },
  {
    id: "agd-3",
    code: "PC-100003",
    cancel_token: "tok-sec-agd-3",
    cliente_id: "cli-3",
    cliente_nome: "Mariana Lima",
    cliente_whatsapp: "71999881122",
    veiculo_id: "veic-3",
    veiculo_tipo: "SUV",
    veiculo_modelo: "Jeep Compass",
    veiculo_placa: "RDM8F22",
    servico_id: "srv-5",
    servico_nome: "Lavagem + aspiração + cera líquida + hidratação de carro SUV",
    valor: 80.0,
    data: getTodayDateString(),
    horario: "10:30",
    status: "Confirmado",
    observacoes: "Cliente avisou que vai aguardar na recepção",
    created_at: "2026-10-01T08:00:00Z",
  },
  {
    id: "agd-4",
    code: "PC-100004",
    cancel_token: "tok-sec-agd-4",
    cliente_id: "cli-4",
    cliente_nome: "Roberto Alves",
    cliente_whatsapp: "71981112233",
    veiculo_id: "veic-4",
    veiculo_tipo: "Caminhonete",
    veiculo_modelo: "Toyota Hilux",
    veiculo_placa: "OZT9B77",
    servico_id: "srv-6",
    servico_nome: "Lavagem + aspiração de caminhonete simples",
    valor: 80.0,
    data: getTodayDateString(),
    horario: "11:30",
    status: "Aguardando",
    observacoes: "Aguardando liberação do box de caminhonetes",
    created_at: "2026-10-01T08:30:00Z",
  },
  {
    id: "agd-5",
    code: "PC-100005",
    cancel_token: "tok-sec-agd-5",
    cliente_id: "cli-5",
    cliente_nome: "Lucas Ferreira",
    cliente_whatsapp: "71987654321",
    veiculo_id: "veic-5",
    veiculo_tipo: "Moto",
    veiculo_modelo: "Honda CG 160",
    veiculo_placa: "RKY3C44",
    servico_id: "srv-1",
    servico_nome: "Lavagem simples de moto",
    valor: 30.0,
    data: getTodayDateString(),
    horario: "14:00",
    status: "Finalizado",
    observacoes: "Entregue e pago em dinheiro",
    created_at: "2026-10-01T09:00:00Z",
  },
  {
    id: "agd-6",
    code: "PC-100006",
    cancel_token: "tok-sec-agd-6",
    cliente_nome: "Rodrigo Mendes",
    cliente_whatsapp: "71992223344",
    veiculo_tipo: "SUV",
    veiculo_modelo: "Hyundai Creta",
    veiculo_placa: "SHY4G12",
    servico_id: "srv-4",
    servico_nome: "Lavagem + aspiração de carro SUV simples",
    valor: 60.0,
    data: getTodayDateString(),
    horario: "15:30",
    status: "Agendado",
    observacoes: "Agendamento realizado pelo site",
    created_at: "2026-10-01T10:00:00Z",
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: "pay-1",
    appointment_id: "agd-1",
    amount: 60.0,
    payment_method: "pix",
    status: "paid",
    paid_at: `${getTodayDateString()}T09:15:00Z`,
    notes: "Pago via chave PIX CNPJ do lava-jato",
    created_at: `${getTodayDateString()}T09:15:00Z`,
    updated_at: `${getTodayDateString()}T09:15:00Z`,
  },
  {
    id: "pay-2",
    appointment_id: "agd-5",
    amount: 30.0,
    payment_method: "dinheiro",
    status: "paid",
    paid_at: `${getTodayDateString()}T14:40:00Z`,
    notes: "Recebido em dinheiro em mãos",
    created_at: `${getTodayDateString()}T14:40:00Z`,
    updated_at: `${getTodayDateString()}T14:40:00Z`,
  },
];

export const INITIAL_CASH_REGISTERS: CashRegister[] = [
  {
    id: "reg-1",
    opened_at: `${getTodayDateString()}T07:45:00Z`,
    closed_at: null,
    opening_balance: 100.0, // Fundo de troco inicial
    closing_balance: null,
    counted_balance: null,
    difference: null,
    status: "open",
    notes: "Caixa aberto com troco inicial padrão",
    created_at: `${getTodayDateString()}T07:45:00Z`,
    updated_at: `${getTodayDateString()}T07:45:00Z`,
  },
];

export const INITIAL_CASH_MOVEMENTS: CashMovement[] = [
  {
    id: "mov-1",
    cash_register_id: "reg-1",
    appointment_id: "agd-5",
    payment_id: "pay-2",
    type: "income",
    category: "Pagamento de Atendimento",
    amount: 30.0,
    payment_method: "dinheiro",
    description: "Lavagem de moto #PC-100005 (Lucas Ferreira)",
    created_at: `${getTodayDateString()}T14:40:00Z`,
  },
  {
    id: "mov-2",
    cash_register_id: "reg-1",
    appointment_id: null,
    payment_id: null,
    type: "expense",
    category: "Material de limpeza",
    amount: 25.0,
    payment_method: "dinheiro",
    description: "Compra emergencial de panos de microfibra",
    created_at: `${getTodayDateString()}T11:00:00Z`,
  },
];

export const INITIAL_COMMUNICATION_LOGS: CommunicationLog[] = [
  {
    id: "comm-1",
    customer_id: "cli-1",
    appointment_id: "agd-1",
    channel: "whatsapp",
    type: "confirmation",
    message_preview: "Olá, João Silva! Seu agendamento no Point do Coco Lava Jato foi confirmado para hoje...",
    status: "opened",
    created_by: null,
    customer_name: "João Silva",
    customer_phone: "71991234567",
    appointment_code: "PC-100001",
    created_at: `${getTodayDateString()}T07:45:00Z`,
  },
  {
    id: "comm-2",
    customer_id: "cli-2",
    appointment_id: "agd-2",
    channel: "whatsapp",
    type: "reminder",
    message_preview: "Olá, Carlos Santos! Passando para lembrar do seu atendimento no Point do Coco Lava Jato...",
    status: "opened",
    created_by: null,
    customer_name: "Carlos Santos",
    customer_phone: "71988776655",
    appointment_code: "PC-100002",
    created_at: `${getTodayDateString()}T08:30:00Z`,
  },
];

export const INITIAL_VEHICLE_CHECKINS: VehicleCheckin[] = [
  {
    id: "chk-1",
    appointment_id: "agd-2",
    vehicle_id: "veic-2",
    customer_id: "cli-2",
    mileage: 45280,
    fuel_level: "1/2",
    interior_condition: "bom",
    exterior_condition: "regular",
    objects_left_in_vehicle: "Óculos escuros no console e guarda-chuva no banco traseiro.",
    general_notes: "Cliente solicitou atenção especial na remoção de poeira da grade frontal.",
    confirmed_by: "usr-employee-1",
    confirmed_by_name: "Rafael Operador",
    confirmed_at: `${getTodayDateString()}T08:50:00Z`,
    status: "completed",
    created_at: `${getTodayDateString()}T08:50:00Z`,
    updated_at: `${getTodayDateString()}T08:50:00Z`,
    checklist_items: [
      { id: "it-1", checkin_id: "chk-1", category: "exterior", item_key: "para_choque_dianteiro", item_label: "Para-choque dianteiro", status: "ok" },
      { id: "it-2", checkin_id: "chk-1", category: "exterior", item_key: "para_choque_traseiro", item_label: "Para-choque traseiro", status: "damaged", notes: "Pequeno amassado no canto direito" },
      { id: "it-3", checkin_id: "chk-1", category: "exterior", item_key: "capo", item_label: "Capô", status: "ok" },
      { id: "it-4", checkin_id: "chk-1", category: "exterior", item_key: "teto", item_label: "Teto", status: "ok" },
      { id: "it-5", checkin_id: "chk-1", category: "exterior", item_key: "porta_dianteira_dir", item_label: "Porta dianteira direita", status: "damaged", notes: "Risco superficial perto da maçaneta" },
      { id: "it-6", checkin_id: "chk-1", category: "interior", item_key: "bancos", item_label: "Bancos e Estofamento", status: "ok" },
      { id: "it-7", checkin_id: "chk-1", category: "interior", item_key: "painel", item_label: "Painel e Multimídia", status: "ok" },
      { id: "it-8", checkin_id: "chk-1", category: "interior", item_key: "tapetes", item_label: "Tapetes", status: "ok" },
      { id: "it-9", checkin_id: "chk-1", category: "accessories", item_key: "estepe", item_label: "Estepe", status: "ok" },
      { id: "it-10", checkin_id: "chk-1", category: "accessories", item_key: "macaco", item_label: "Macaco", status: "ok" },
      { id: "it-11", checkin_id: "chk-1", category: "accessories", item_key: "chave_roda", item_label: "Chave de roda", status: "ok" },
      { id: "it-12", checkin_id: "chk-1", category: "accessories", item_key: "triangulo", item_label: "Triângulo de segurança", status: "ok" },
    ],
    damages: [
      {
        id: "dam-1",
        checkin_id: "chk-1",
        vehicle_id: "veic-2",
        type: "risco",
        location: "lateral_direita",
        specific_part: "Porta dianteira direita",
        severity: "leve",
        description: "Risco superficial longitudinal próximo à maçaneta externa.",
        photo_url: null,
        created_by: "usr-employee-1",
        created_at: `${getTodayDateString()}T08:52:00Z`,
      },
      {
        id: "dam-2",
        checkin_id: "chk-1",
        vehicle_id: "veic-2",
        type: "amassado",
        location: "traseira",
        specific_part: "Para-choque traseiro",
        severity: "media",
        description: "Amassado de ~4cm no canto inferior direito do para-choque.",
        photo_url: null,
        created_by: "usr-employee-1",
        created_at: `${getTodayDateString()}T08:53:00Z`,
      },
    ],
    photos: [
      {
        id: "pho-1",
        checkin_id: "chk-1",
        vehicle_id: "veic-2",
        storage_path: "inspections/veic2_frente.jpg",
        photo_url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=60",
        photo_type: "front",
        description: "Frente do veículo na entrada do lava-jato",
        created_by: "usr-employee-1",
        created_at: `${getTodayDateString()}T08:54:00Z`,
      },
      {
        id: "pho-2",
        checkin_id: "chk-1",
        vehicle_id: "veic-2",
        storage_path: "inspections/veic2_traseira.jpg",
        photo_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=60",
        photo_type: "rear",
        description: "Visão traseira e detalhe do para-choque",
        created_by: "usr-employee-1",
        created_at: `${getTodayDateString()}T08:55:00Z`,
      },
    ],
  },
];

export const INITIAL_CUSTOMER_TAGS: CustomerTag[] = [
  { id: "tag-1", name: "VIP", color: "#EAB308", description: "Cliente de alto valor ou alta frequência", created_at: "2026-09-01T00:00:00Z" },
  { id: "tag-2", name: "Recorrente", color: "#10B981", description: "Cliente frequente com múltiplos atendimentos", created_at: "2026-09-01T00:00:00Z" },
  { id: "tag-3", name: "Novo", color: "#38BDF8", description: "Cliente em seu primeiro atendimento", created_at: "2026-09-01T00:00:00Z" },
  { id: "tag-4", name: "Inativo", color: "#94A3B8", description: "Cliente sem retorno há mais de 60 dias", created_at: "2026-09-01T00:00:00Z" },
  { id: "tag-5", name: "Frotista / Empresa", color: "#A855F7", description: "Atendimento corporativo ou frotas", created_at: "2026-09-01T00:00:00Z" },
  { id: "tag-6", name: "Indicado", color: "#F97316", description: "Cliente indicado por parceiro ou amigo", created_at: "2026-09-01T00:00:00Z" },
];

export const INITIAL_CUSTOMER_TAG_ASSIGNMENTS: CustomerTagAssignment[] = [
  { id: "cta-1", customer_id: "cli-1", tag_name: "VIP", created_by: "usr-admin-1", created_at: "2026-09-10T10:00:00Z" },
  { id: "cta-2", customer_id: "cli-1", tag_name: "Recorrente", created_by: "usr-admin-1", created_at: "2026-09-10T10:00:00Z" },
  { id: "cta-3", customer_id: "cli-2", tag_name: "Recorrente", created_by: "usr-admin-1", created_at: "2026-09-15T10:00:00Z" },
  { id: "cta-4", customer_id: "cli-4", tag_name: "Frotista / Empresa", created_by: "usr-admin-1", created_at: "2026-09-25T10:00:00Z" },
];

export const INITIAL_SERVICE_REVIEWS: ServiceReview[] = [
  {
    id: "rev-1",
    appointment_id: "agd-1",
    customer_id: "cli-1",
    rating: 5,
    comment: "Excelente atendimento! O carro ficou impecável e a aspiração perfeita.",
    created_by: "usr-admin-1",
    created_at: `${getTodayDateString()}T09:00:00Z`,
    updated_at: `${getTodayDateString()}T09:00:00Z`,
    customer_name: "Ana Silva",
    service_name: "Lavagem + aspiração de carro pequeno simples",
    vehicle_plate: "BRA2E19",
  },
  {
    id: "rev-2",
    appointment_id: "agd-2",
    customer_id: "cli-2",
    rating: 4,
    comment: "Muito bom serviço, pontual e atencioso.",
    created_by: "usr-admin-1",
    created_at: `${getTodayDateString()}T10:00:00Z`,
    updated_at: `${getTodayDateString()}T10:00:00Z`,
    customer_name: "Carlos Santos",
    service_name: "Lavagem + aspiração de carro pequeno simples",
    vehicle_plate: "PKT4A90",
  },
];




